config/routes.rb
Rails.application.routes.draw do
  root to:"homes#top"
  devise_for :users

  get '/home/about' => 'homes#about', as: 'about'
  # 検索機能
  get "search" => "searches#search"
  get "search_tag" => "books#search_tag"

  resources :books,only: [:create,:index,:show,:edit,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # usersの中にフォローをネストさせる
  resources :users,only: [:show,:index,:edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  patch 'users/:id' => 'users#update', as: 'update_user'
  patch 'books/:id' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books,dependent: :destroy
         has_many :favorites,dependent: :destroy
         has_many :book_comments, dependent: :destroy

        # フォローをした、されたの関係
        has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
        has_many :followings, through: :relationships, source: :followed  #自分がフォローしている人の一覧表示のための記述

        has_many :reverce_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
        has_many :followers, through: :reverce_of_relationships, source: :follower #自分がフォローされている人の一覧表示のための記述

        # ユーザーをフォローする定義
        def follow(user_id)
          relationships.create(followed_id: user_id)
        end

        # ユーザのフォローを外す定義
        def unfollow(user_id)
          relationships.find_by(followed_id: user_id).destroy
        end

        # ユーザをフォローしているかの判定
        def following?(user)
          followings.include?(user)
        end

        # user検索方法分岐
        def self.looks(search, word)
          if search == "perfect_match"
            @user = User.where("name LIKE?", "#{word}")
          elsif search == "forward_match"
            @user = User.where("name LIKE?", "#{word}%")
          elsif search == "backward_match"
            @user = User.where("name LIKE?", "%#{word}")
          elsif search == "partial_match"
            @user = User.where("name LIKE?", "%#{word}%")
          else
            @user = User.all
          end
        end

  has_one_attached :profile_image
  # バリデーション
  validates :name,presence: true,uniqueness: true,length: {minimum:2, maximum:20}
  validates :introduction,length: {maximum:50}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 他の人が自分のユーザ情報をいじれないようにする
  before_action :is_matching_login_user, only: [:edit,:update]
  

  def show
    @book = Book.new
    # showで見ているユーザidのユーザを指定
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    # 他の人が自分のユーザ情報をいじれないようにする
    # is_matching_login_user

    @user = User.find(params[:id])
  end

  def update
    # 他の人が自分のユーザ情報をいじれないようにする
    # is_matching_login_user

    @user = User.find(params[:id])
    # バリデーションに抵触した場合、そのページに留まります
    if @user.update(user_params)
      # フラッシュメッセージを設定
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  private

  def user_params
    # ここに、画像も許可する記述が必要
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  # 他の人が自分のユーザ情報をいじれないようにする
  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <% if user.profile_image.attached? %>
            <%= image_tag user.profile_image, size: "100x100" %>
          <% else %>
            <%= image_tag 'no_image', size: "100x100" %>
          <% end %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td><p>フォロー数：<%= user.followings.count %></p></td>
        <td><p>フォロワー数：<%= user.followers.count %></p></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show" ,user_path(user.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
       <!--画像-->
        <% if user.profile_image.attached? %>
          <%= image_tag user.profile_image, size: "100x100" %>
        <% else %>
          <%= image_tag 'no_image', size: "100x100" %>
        <% end %>

      <table class ="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to user_followings_path(user.id),method: :get do %>
                <%= user.followings.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to user_followers_path(user.id),method: :get do %>
                <%= user.followers.count %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>

      <!--ログインユーザだったらエディットボタン、そうでなかったらフォローボタンを表示-->
      <% if user == current_user %>
        <div class ="row">
          <%= link_to edit_user_path(user.id), class: ' btn btn-outline-secondary btn-block' do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
      <% else %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary"%>
        <% end %>
      <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">

      <h1>User info</h1>

      <!--バリデーションメッセージ-->
      <% if @user.errors.any? %>
        <p><%= @user.errors.count %>errors prohibited this obj from being saved:</p>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>

        <h4>Name</h4>
        <%= f.text_field :name %>

        <h4>Image</h4>
        <%= f.file_field :profile_image,accept: "image/*" %>

        <h4>Introduction</h4>
        <%= f.text_area :introduction %>

        <p><%= f.submit 'Update User',class:"btn btn-secondary" %></p>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <!--books#createのバリデーションメッセージ-->
  <% if @book.errors.any? %>
    <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <h1>User info</h1>
        <%= render 'info', user: current_user %>

      <h2>New book</h1>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!--user一覧-->
      <!--投稿したユーザの画像を表示するところから実装します-->
      <h1>Users</h1>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div>
  <%= flash[:notice] %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <!--ユーザの情報を表示-->
      <h1>User info</h1>
      <%= render 'info', user: @user %>

      <!--新規投稿-->
      <%= render 'books/form', book: @book %>
    </div>

    <dic class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <%= render 'books/index', books: @books %>
    </dic>
  </div>
</div>