config/routes.rb
Rails.application.routes.draw do
  root to:"homes#top"
  devise_for :users

  get '/home/about' => 'homes#about', as: 'about'
  # 検索機能
  get "search" => "searches#search"
  get "search_tag" => "books#search_tag"

  resources :books,only: [:create,:index,:show,:edit,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # usersの中にフォローをネストさせる
  resources :users,only: [:show,:index,:edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  patch 'users/:id' => 'users#update', as: 'update_user'
  patch 'books/:id' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  # 画像を許可
  has_one_attached :image
  belongs_to:user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

    # book検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end

  # バリデーション
  validates :title,presence: true
  validates :body,presence: true, length: {maximum:200}

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}



  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # タグ検索のための記述
  def self.search(search_word)
    Book.where(['category LIKE ?',"#{search_word}"])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # 他の人が自分のユーザ情報をいじれないようにする
  before_action :is_matching_login_user, only: [:edit,:update]

  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    # バリデーションを実装
    if @book.save
      # フラッシュメッセージを設定
      flash[:notice] = "You have created book successfully."
      # 【済】books#showにリダイレクトしないといけない
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      # フラッシュメッセージを設定
      flash[:notice] = "You have update book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy #レコード削除
    redirect_to books_path
  end

  def index
    @book = Book.new
    # @books = Book.all
    @user = current_user

    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.new
    @show_book = Book.find(params[:id])
    # showにおける本の感想を書いたuserの情報を出したい
    @user = User.find(@show_book.user_id)
    @book_comment = BookComment.new

    # のちのちのための記述。userコントローラのshowにて記述
    # @user = current_user
    # @books = @user.books
  end

  # タグ検索
  def search_tag
    @book = Book.new
    @books = Book.search(params[:keyword])
  end



  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title,:body,:star,:category)
  end

  def user_params
    # 【済】ここに、画像も許可する記述が必要
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  # 他の人が自分の投稿内容をいじれないようにする
  def is_matching_login_user
    book_user_id = Book.find(params[:id]).user.id.to_i
    login_user_id = current_user.id
    if(book_user_id != login_user_id)
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <label>カテゴリ</label>
  <p><%= f.text_field :category %></p>

  <!--星評価-->
  <div id="star">
    <!--< %= f.label :star,'評価' %>-->
      <%= f.hidden_field :star, id: :review_star, class:'form-control' %>
  </div>
  <div id="post-star"></div>
  <script>
  // scriptファイルをどのidの部分に配置するかを指定
  $(document).on('turbolinks:load', function() {
    let elem = document.querySelector('#post-star');
    elem.innerHTML = ""
    let opt = {
      //星画像の指定などのオプションをここに記述,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[star]',
      half: true
     };
    raty(elem,opt);
  });
  </script>

  <%= f.submit 'Create Book', class: "btn btn-success"%>



<% end %>

app/views/books/_index.html.erb
<p>
  <%= link_to '新しい順', books_path(latest: "true") %>
  |<%= link_to '古い順', books_path(old: "true") %>
  |<%= link_to '評価の高い順', books_path(star_count: "true") %>
</p>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <p><%= image_tag book.user.get_profile_image(100,100) %></p>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <span><%= book.body %></span>
        </td>

        <!--タグ-->
        <% if book.category.present? %>
          <td><%= link_to book.category, search_tag_path(keyword: book.category) %></td>
        <% else %>
          <td>ー</td>
        <% end %>

        <!--いいね機能-->
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>
          <p>コメント数：<%= book.book_comments.count %></p>
        </td>
        <td>
          <div id="star-<%= book.id %>"></div>
        </td>
      </tr>

      <script>
      // scriptファイルをどのidの部分に配置するかを指定
      elem = document.querySelector('#star-<%= book.id %>');
      opt = {
        //星画像の指定などのオプションをここに記述,
        starOff: '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'book[star]',
        half: true,
        readOnly: true,
        score: <%= book.star %>
       };
      raty(elem,opt);
      </script>

    <% end %>
  </tbody>
</table>

app/views/books/_star.html.erb
<!--評価javascript-->

<div class="form-group row" id="star">
  <%= book.label :star,'評価', class:'col-md-3 col-form-label' %>
  <%= book.hidden_field :star, id: :review_star %>
</div>

<script>
  $('#star').raty({
    size:36,
    starOff: '<%= asset_path('star-off.png') %>'
    starOn : '<%= asset_path('star-on.png')'
  })
</script>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <!--books#newのバリデーションメッセージ-->
      <% if @book.errors.any? %>
        <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <h2>Editing Book</h2>

      <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

        <p>Title</p>
        <%= f.text_field :title %>

        <p>Opinion</p>
        <%= f.text_area :body %>

        <div id="star-<%= @book.id %>"></div>

        <p><%= f.submit 'Update Book',class:"btn btn-success" %></p>

        <p>
          <%= link_to "Show", book_path(@book.id) %>
          | <%= link_to "Back", books_path %>
        </p>

        <% end %>

    </div>
  </div>
</div>

<script>
// scriptファイルをどのidの部分に配置するかを指定
elem = document.querySelector('#star-<%= @book.id %>');
opt = {
  //星画像の指定などのオプションをここに記述,
  starOff: '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'book[star]',
  half: true,
  readOnly: true,
  score: <%= @book.star %>
 };
raty(elem,opt);
</script>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <!--books#createのバリデーションメッセージ-->
  <% if @book.errors.any? %>
    <p><%= @book.errors.count %>errors prohibited this obj from being saved:</p>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class ="row">
    <div class ="col-md-3">
      <h1>User info</h1>
      <%= render 'users/info', user: current_user %>
      <h1 class="mt-3">New book</h1>
      <%= render 'form', book: @book %>
    </div>
    <div class = "col-md-8 offset-md-1">
      <h1>Books</h1>
      <%= render 'index', books: @books %>
   </div>
  </div>
</div>

app/views/books/search_tag.html.erb
<h2>Books search for "<%= params[:keyword] %>"</h2>

<%= render 'index', books: @books %>

app/views/books/show.html.erb
<div class="container">
  <div>
  <%= flash[:notice] %>
  </div>
  <div class = "row">
    <div class ="col-md-3">
      <h1>User info</h1>
      <%= render 'users/info', user: @show_book.user %>


      <h1>New book</h1>
      <%= render 'form', book: @book %>
    </div>

    <div class ="col-md-8 offset-md-1">
      <!--showの部分-->
      <!--ユーザの画像を表示するところ-->
      <h2>Book detail</h2>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <p><%= image_tag @user.get_profile_image(100,100) %></p>
                <p><%= @user.name %></p>
              <% end %>
            </td>
            <td>
              <%= link_to @show_book.title, book_path(@show_book.id) %>
            </td>
            <td>
              <span><%= @show_book.body %></span>
            </td>
            <!--いいね機能-->
            <td id="favorite_buttons_<%= @show_book.id %>">
              <%= render "favorites/favorite", book: @show_book %>
            </td>
            <!--コメント数機能-->
            <td>
              <p>コメント数：<%= @show_book.book_comments.count %></p>
            </td>
            <td>
              <div id="star-<%= @show_book.id %>"></div>
            </td>

            <%if @show_book.user == current_user %>
              <td>
                <!--Editボタン-->
                <%= link_to "Edit", edit_book_path(@show_book.id), class: ' btn btn-success' %>
              </td>
              <td>
                <!--Destroyボタン-->
                <%= link_to "Destroy", book_path(@show_book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: ' btn btn-danger' %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <!--コメント投稿内容-->

          <div id="book_comments"><%= render "book_comments/book_comment_index", book: @show_book %></div>


      <!--コメント投稿するところ-->
      <div id="book_comment_form"><%= render "book_comments/book_comment_form", book: @show_book,book_comment: @book_comment %></div>
    </div>
  </div>
</div>


<script>
// scriptファイルをどのidの部分に配置するかを指定
elem = document.querySelector('#star-<%= @show_book.id %>');
opt = {
  //星画像の指定などのオプションをここに記述,
  starOff: '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  starHalf: '<%= asset_path('star-half.png') %>',
  scoreName: 'book[star]',
  half: true,
  readOnly: true,
  score: <%= @show_book.star %>
 };
raty(elem,opt);
</script>