config/routes.rb
Rails.application.routes.draw do
  root to:"homes#top"
  devise_for :users

  get '/home/about' => 'homes#about', as: 'about'
  # 検索機能
  get "search" => "searches#search"
  get "search_tag" => "books#search_tag"

  resources :books,only: [:create,:index,:show,:edit,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # usersの中にフォローをネストさせる
  resources :users,only: [:show,:index,:edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  patch 'users/:id' => 'users#update', as: 'update_user'
  patch 'books/:id' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand p-3" href="/">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <!--<a class="nav-link text-light" href = user_path(current_user.id)>Home</a>-->
          <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
            <p><i class="fas fa-home"></i> Home</p>
          <% end %>
        </li>
        <li class="nav-item text-white">
          <%= link_to  users_path, class: 'nav-link text-light' do %>
            <p><i class="fas fa-users"></i> Users</p>
          <% end %>
        </li>
        <li class="nav-item text-white">
          <%= link_to books_path, class: 'nav-link text-light' do %>
            <p><i class="fas fa-book-open"></i> Books</p>
          <% end %>
        </li>
        <li class="nav-item text-white">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <p><i class="fas fa-sign-out-alt"></i> Log out</p>
          <% end %>
        </li>
        <% else %>
        <li class="nav-item text-white">
          <%= link_to root_path, class: 'nav-link text-light' do %>
            <p><i class="fas fa-home"></i> Home</p>
          <% end %>
        </li>
        <li class="nav-item text-white">
          <%= link_to  about_path, class: 'nav-link text-light' do%>
            <p><i class="fas fa-link"></i> About</p>
          <% end %>
        </li>
        <li class="nav-item text-white">
          <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
            <p><i class="fas fa-user-plus"></i> Sign up</p>
          <% end %>
        </li>
        <li class="nav-item text-white">
          <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
            <p><i class="fas fa-sign-in-alt"></i> Log in</p>
          <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


<% if user_signed_in? %>
  <!--検索機能-->
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <a><%= f.text_field :word %></a>
    <a><%= f.select :range, options_for_select([['User'],['Book']]) %></a>
    <a><%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","background_match"],["部分一致","partial_match"]]) %></a>
    <a><%= f.submit "検索", class: "btn btn-primary" %></a>
  <% end %>
  <!--タグ検索機能-->
  <%= form_with url: search_tag_path, local: true, method: :get do |f| %>
    <a><%= f.text_field :keyword %></a>
    <a><%= f.submit "タグ検索", class: "btn btn-primary" %></a>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">-->
  </head>


  <body>
    <!--ヘッダ-->
    <%= render 'layouts/header' %>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <!--フッタ-->
    <%= render 'layouts/footer' %>

  </body>
</html>